name: Push Docker Image to docker
on:
  push:
    branches:
    - master
  workflow_dispatch:
env: 
  IMAGENM: "rachelleecp/httpapp:v2"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check Weather Docker is there or not.
        run: |
          docker version
          echo "$IMAGENM"
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push

        uses: docker/build-push-action@v3
        with:
          push: true
          tags: $IMAGENM
          images: $IMAGENM

